import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { LingoProvider } from "@lingo.dev/compiler/react";
import "@/app/globals.css";
import * as React from "react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string | undefined }>
  }) {
  const { locale }: { locale: string | undefined } = React.use(params)
  console.log(locale)
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
